<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-karelcuevas/blob/main/assignment01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('assignment01 for GitJobish03 and edited in git, and 18')

assignment01 for GitJobish03 and edited in git, and 18


In [ ]:
#print ("Hello Python")
print ("Hello Python 101")

In [ ]:
print("Hello\nWorld!")

Hello
World!


In [ ]:
# print('Hello World!')

In [ ]:
bool(1)

True

In [ ]:
# Check the Python Version

import sys
print(sys.version)

3.7.14 (default, Sep  8 2022, 00:06:44) 
[GCC 7.5.0]


In [ ]:
# Practice on writing comments

print('Hello, Python!') # This line prints a string
# print('Hi')

Hello, Python!


In [ ]:
# Print string as error message

frint("Hello, Python!")

NameError: ignored

In [ ]:
# Try to see built-in error message

print("Hello, Python!)

SyntaxError: ignored

In [ ]:
# Print string and error to see the running order

print("This will be printed")
frint("This will cause an error")
print("This will NOT be printed")

This will be printed


NameError: ignored

In [ ]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell
print("Hello, world!")

Hello, world!


In [ ]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell
print("Hello, world!") #Print the traditional hello world

Hello, world!


In [ ]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell
type(12.0)

float

In [ ]:
# System settings about float type

sys.float_info

sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)

In [ ]:
type(float(2))

float

In [ ]:
float("1.2")

1.2

In [ ]:
type (6/2)
type (6//2)

int

In [ ]:
x = 43 + 60 + 16 + 41
print(x)

160


In [ ]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell
x = 3+2*2 #7
x

# Write your code below. Don't forget to press Shift+Enter to execute the cell
y = (3 + 2) * 2 #10
y

z=x+y
z

17

In [ ]:
e = 'clocrkr1e1c1t'
print(e[::2])

correct


In [ ]:
print(r"\ ")

\ 


In [ ]:
# Write your code below and press Shift+Enter to execute

f = "You are wrong"
print(f.upper())

YOU ARE WRONG


In [ ]:
# Write your code below and press Shift+Enter to execute

g = "Mary had a little lamb Little lamb, little lamb Mary had a little lamb \
Its fleece was white as snow And everywhere that Mary went Mary went, Mary went \
Everywhere that Mary went The lamb was sure to go"
g.find('snow')

95

In [ ]:
# Write your code below and press Shift+Enter to execute
g.replace('Mary', 'Bob')

'Bob had a little lamb Little lamb, little lamb Bob had a little lamb Its fleece was white as snow And everywhere that Bob went Bob went, Bob went Everywhere that Bob went The lamb was sure to go'

In [ ]:
A=(0,1,2,3) 
type (A)
print(A[0:2])




(0, 1)


In [ ]:
B=["a","b","c"]
print(B[0:2])
B[0]=B[0].upper()
B[1:]
B.append(['f','g'])
B

['a', 'b']


['A', 'b', 'c', ['f', 'g']]

In [ ]:
['A','B','C','A','B','C']
set(['A','B','C','A','B','C'])
S={'A','B','C'}
S.add("D")
S

A={1,2,3,4,5}
B={1,3,9, 12}
A&B

{1, 3}

In [ ]:
D={'a':0,'b':1,'c':2}
D["a"]
D.keys()

dict_keys(['a', 'b', 'c'])

In [ ]:
# sample tuple

genres_tuple = ("pop", "rock", "soul", "hard rock", "soft rock", \
                "R&B", "progressive rock", "disco") 
genres_tuple
len(genres_tuple)
genres_tuple[3]
genres_tuple[3:6]
genres_tuple.index("disco")


7

In [ ]:
C_tuple=(-5, 1, -3)
sorted(C_tuple)

[-5, -3, 1]

In [ ]:
a_list=[1,"hello",[1,2,3],True]
a_list
print(a_list[1])
a_list[1:4]

hello


['hello', [1, 2, 3], True]

In [ ]:
A = [1, 'a']
B = [2, 1, 'd']
A+B

[1, 'a', 2, 1, 'd']

In [ ]:
set(['rap','house','electronic music','rap'])

{'electronic music', 'house', 'rap'}

In [ ]:
A = [1, 2, 2, 1]
B = set([1, 2, 2, 1])
sum(A) == sum(B)

False

In [ ]:
album_set1 = set(["Thriller", 'AC/DC', 'Back in Black'])
album_set2 = set([ "AC/DC", "Back in Black", "The Dark Side of the Moon"])
album_set3 = album_set1.union(album_set2)
print(album_set3)
album_set1.issubset(album_set3)

{'The Dark Side of the Moon', 'AC/DC', 'Thriller', 'Back in Black'}


True

In [ ]:
soundtrack_dic = {"The Bodyguard":"1992", "Saturday Night Fever":"1977"}
print(soundtrack_dic)
print(soundtrack_dic.keys())
print(soundtrack_dic.values())

{'The Bodyguard': '1992', 'Saturday Night Fever': '1977'}
dict_keys(['The Bodyguard', 'Saturday Night Fever'])
dict_values(['1992', '1977'])


In [ ]:
album_sales_dict = {"The Bodyguard":50, "Back in Black":50, "Thriller":65}
print(album_sales_dict)
print(album_sales_dict["Thriller"])
album_sales_dict.values()


{'The Bodyguard': 50, 'Back in Black': 50, 'Thriller': 65}
65


dict_values([50, 50, 65])

In [ ]:
i=1
i!=0

True

In [ ]:
x = 'a'
if(x=='a'):
    print("this is a")
else:
    print("this is  not a")

this is a


In [ ]:
y=9
x=1
x>0 and y<10

True

In [ ]:
# Write your code below and press Shift+Enter to execute
r=9
if r>8:
    print("This album is amazing!")

This album is amazing!


In [ ]:
# Write your code below and press Shift+Enter to execute
r = 9
if r > 8:
    print ("this album is amazing")
else:
    print ("this album is ok")

this album is amazing


In [ ]:
# Write your code below and press Shift+Enter to execute
album_year = 1970

if album_year < 1980 or album_year == 1991 or album_year == 1993:
    print("This album came out in year", album_year)

This album came out in year 1970


In [ ]:
# Write your code below and press Shift+Enter to execute
for i in range(-4,5):
        print(i)

-4
-3
-2
-1
0
1
2
3
4


In [ ]:
# Write your code below and press Shift+Enter to execute
Genres = ['rock', 'R&B', 'Soundtrack', 'R&B', 'soul', 'pop']
for i in Genres:
    print(i)

rock
R&B
Soundtrack
R&B
soul
pop


In [ ]:
# Write your code below and press Shift+Enter to execute
squares=['red', 'yellow', 'green', 'purple', 'blue']
for i in squares:
        print (i)

red
yellow
green
purple
blue


In [ ]:
# Write your code below and press Shift+Enter to execute
PlayListRatings = [10, 9.5, 10, 8, 7.5, 5, 10, 10]
i=0
r=PlayListRatings[0]
while(i < len(PlayListRatings) and r>=6):
    print(r)
    i=i+1
    r=PlayListRatings[i]

10
9.5
10
8
7.5


In [ ]:
# Write your code below and press Shift+Enter to execute

squares = ['orange', 'orange', 'purple', 'blue ', 'orange']
new_squares = []
squares = ['orange', 'orange', 'purple', 'blue ', 'orange']
new_squares = []
i = 0
while(i < len(squares) and squares[i] == 'orange'):
    new_squares.append(squares[i])
    i = i + 1
print (new_squares)

['orange', 'orange']


In [ ]:
def g(c):

    return sum(c)

c=[1,2,3,4,5]

if sum(c)==g(c):   
    print("Correct.")   
else:    
    print("Incorrect.")

Correct.


In [ ]:
# Write your code below and press Shift+Enter to execute
def divide(a,b):
    return (a/b)

In [ ]:
# Write your code below and press Shift+Enter to execute
def con(a, b):
    return(a + b)
print (con(2,2))
print (con ("hola ","cara de bola"))
con(['a', 1], ['b', 1])

4
hola cara de bola


['a', 1, 'b', 1]

In [ ]:
class analysedText(object):
    
    def __init__ (self, text):
        # remove punctuation
        formattedText = text.replace('.','').replace('!','').replace('?','').replace(',','')
        
        # make text lowercase
        formattedText = formattedText.lower()
        
        self.fmtText = formattedText
        
    def freqAll(self):        
        # split text into words
        wordList = self.fmtText.split(' ')
        
        # Create dictionary
        freqMap = {}
        for word in set(wordList): # use set to remove duplicates in list
            freqMap[word] = wordList.count(word)
        
        return freqMap
    
    def freqOf(self,word):
        # get frequency map
        freqDict = self.freqAll()
        
        if word in freqDict:
            return freqDict[word]
        else:
            return 0
    

    import sys

sampleMap = {'eirmod': 1,'sed': 1, 'amet': 2, 'diam': 5, 'consetetur': 1, 'labore': 1, 'tempor': 1, 'dolor': 1, 'magna': 2, 'et': 3, 'nonumy': 1, 'ipsum': 1, 'lorem': 2}

def testMsg(passed):
    if passed:
       return 'Test Passed'
    else :
       return 'Test Failed'

print("Constructor: ")
try:
    samplePassage = analysedText("Lorem ipsum dolor! diam amet, consetetur Lorem magna. sed diam nonumy eirmod tempor. diam et labore? et diam magna. et diam amet.")
    print(testMsg(samplePassage.fmtText == "lorem ipsum dolor diam amet consetetur lorem magna sed diam nonumy eirmod tempor diam et labore et diam magna et diam amet"))
except:
    print("Error detected. Recheck your function " )
print("freqAll: ")
try:
    wordMap = samplePassage.freqAll()
    print(testMsg(wordMap==sampleMap))
except:
    print("Error detected. Recheck your function " )
print("freqOf: ")
try:
    passed = True
    for word in sampleMap:
        if samplePassage.freqOf(word) != sampleMap[word]:
            passed = False
            break
    print(testMsg(passed))
    
except:
    print("Error detected. Recheck your function  " )
    

Constructor: 
Test Passed
freqAll: 
Test Passed
freqOf: 
Test Passed


In [3]:
# Read the Example1.txt
example1 =  "/content/sample_data/california_housing_test.csv"
file1 = open(example1, "r")
FileContent=file1.read()
#print(FileContent)

In [4]:
with open(example1, "r") as file1:
    FileContent = file1.read()
   # print(FileContent)

In [ ]:
import pandas as pd

df=pd.DataFrame({'a':[11,21,31],'b':[21,22,23]})

In [ ]:
df.head()

Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [ ]:
df['a']

0    11
1    21
2    31
Name: a, dtype: int64

In [ ]:
import pandas as pd

df=pd.DataFrame({'a':[1,2,1],'b':[1,1,1]})

In [ ]:
df['a'].unique()
df[df['a']<2]

a  b
0  1  1
2  1  1

In [ ]:
# Write line to file
exmp2 = 'Example2.txt'
with open(exmp2, 'w') as writefile:
    writefile.write("This is line A")

In [ ]:
# Read file

with open(exmp2, 'r') as testwritefile:
    print(testwritefile.read())

This is line A


In [ ]:
# Write a new line to text file

with open('Example2.txt', 'a') as testwritefile:
    testwritefile.write("This is line C\n")
    testwritefile.write("This is line D\n")
    testwritefile.write("This is line E\n")

In [ ]:
# Verify if the new line is in the text file

with open('Example2.txt', 'r') as testwritefile:
    print(testwritefile.read())

This is line AThis is line C
This is line D
This is line E



In [ ]:
with open('Example2.txt', 'a+') as testwritefile:
    testwritefile.write("This is line E\n")
    print(testwritefile.read())

In [ ]:
with open('Example2.txt', 'a+') as testwritefile:
    print("Initial Location: {}".format(testwritefile.tell()))
    
    data = testwritefile.read()
    if (not data):  #empty strings return false in python
            print('Read nothing') 
    else: 
            print(testwritefile.read())
            
    testwritefile.seek(0,0) # move 0 bytes from beginning.
    
    print("\nNew Location : {}".format(testwritefile.tell()))
    data = testwritefile.read()
    if (not data): 
            print('Read nothing') 
    else: 
            print(data)
    
    print("Location after read: {}".format(testwritefile.tell()) )

Initial Location: 15
Read nothing

New Location : 0
This is line E

Location after read: 15


In [ ]:
#Run this prior to starting the exercise
from random import randint as rnd

memReg = 'members.txt'
exReg = 'inactive.txt'
fee =('yes','no')

def genFiles(current,old):
    with open(current,'w+') as writefile: 
        writefile.write('Membership No  Date Joined  Active  \n')
        data = "{:^13}  {:<11}  {:<6}\n"

        for rowno in range(20):
            date = str(rnd(2015,2020))+ '-' + str(rnd(1,12))+'-'+str(rnd(1,25))
            writefile.write(data.format(rnd(10000,99999),date,fee[rnd(0,1)]))


    with open(old,'w+') as writefile: 
        writefile.write('Membership No  Date Joined  Active  \n')
        data = "{:^13}  {:<11}  {:<6}\n"
        for rowno in range(3):
            date = str(rnd(2015,2020))+ '-' + str(rnd(1,12))+'-'+str(rnd(1,25))
            writefile.write(data.format(rnd(10000,99999),date,fee[1]))


genFiles(memReg,exReg)


In [ ]:
def cleanFiles(currentMem,exMem):
    with open(currentMem,'r+') as writeFile: 
        with open(exMem,'a+') as appendFile:
            #get the data
            writeFile.seek(0)
            members = writeFile.readlines()
            #remove header
            header = members[0]
            members.pop(0)
                
            inactive = [member for member in members if ('no' in member)]
            '''
            The above is the same as 

            for member in members:
            if 'no' in member:
                inactive.append(member)
            '''
            #go to the beginning of the write file
            writeFile.seek(0) 
            writeFile.write(header)
            for member in members:
                if (member in inactive):
                    appendFile.write(member)
                else:
                    writeFile.write(member)      
            writeFile.truncate()
                
memReg = 'members.txt'
exReg = 'inactive.txt'
cleanFiles(memReg,exReg)

# code to help you see the files

headers = "Membership No  Date Joined  Active  \n"

with open(memReg,'r') as readFile:
    print("Active Members: \n\n")
    print(readFile.read())
    
with open(exReg,'r') as readFile:
    print("Inactive Members: \n\n")

Active Members: 


Membership No  Date Joined  Active  
    39118      2016-10-7    yes   
    45806      2018-6-6     yes   
    91974      2018-10-2    yes   
    12663      2017-10-7    yes   
    11332      2016-4-2     yes   
    58286      2017-1-22    yes   
    91004      2018-9-10    yes   

Inactive Members: 




In [ ]:
import pandas as banana

df=banana.DataFrame({'a':[11,21,31],'b':[21,22,23]})

df.head()

a   b
0  11  21
1  21  22
2  31  23

In [ ]:
import pandas as pd

df=pd.DataFrame({'a':[11,21,31],'b':[21,22,23]})
df.head(3)

a   b
0  11  21
1  21  22
2  31  23

In [ ]:
df['a']

0    11
1    21
2    31
Name: a, dtype: int64

In [ ]:
import pandas as pd

df=pd.DataFrame({'a':[1,2,1],'b':[1,1,1]})
df['a'].unique()

array([1, 2])

In [ ]:
df[df['a']<2]

a  b
0  1  1
2  1  1

In [ ]:
# let us import the Pandas Library
import pandas as pd

In [ ]:
#Define a dictionary 'x'

x = {'Name': ['Rose','John', 'Jane', 'Mary'], 'ID': [1, 2, 3, 4], 'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 
      'Salary':[100000, 80000, 50000, 60000]}

#casting the dictionary to a DataFrame
df = pd.DataFrame(x)

#display the result df
df

Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [ ]:
#Retrieving the "ID" column and assigning it to a variable x
x = df[['ID']]
x

ID
0   1
1   2
2   3
3   4

In [ ]:
#check the type of x
type(x)

pandas.core.frame.DataFrame

In [ ]:
#Retrieving the Department, Salary and ID columns and assigning it to a variable z

z = df[['Department','Salary','ID']]
z

Department  Salary  ID
0  Architect Group  100000   1
1   Software Group   80000   2
2      Design Team   50000   3
3   Infrastructure   60000   4

In [ ]:
a = {'Student':['David', 'Samuel', 'Terry', 'Evan'],
     'Age':['27', '24', '22', '32'],
     'Country':['UK', 'Canada', 'China', 'USA'],
     'Course':['Python','Data Structures','Machine Learning','Web Development'],
     'Marks':['85','72','89','76']}
df1 = pd.DataFrame(a)
df1

Student Age Country            Course Marks
0   David  27      UK            Python    85
1  Samuel  24  Canada   Data Structures    72
2   Terry  22   China  Machine Learning    89
3    Evan  32     USA   Web Development    76

In [ ]:
b = df1[['Marks']]
b

Marks
0    85
1    72
2    89
3    76

In [ ]:
c = df1[['Country','Course']]
c


Country            Course
0      UK            Python
1  Canada   Data Structures
2   China  Machine Learning
3     USA   Web Development

In [ ]:
x = df['Name']
x

0    Rose
1    John
2    Jane
3    Mary
Name: Name, dtype: object

In [ ]:
#check the type of x
type(x)

pandas.core.series.Series

In [ ]:
# Access the value on the first row and the first column

df.iloc[0, 0]

'Rose'

In [ ]:
# Access the value on the first row and the third column

df.iloc[0,2]

'Architect Group'

In [ ]:
# Access the column using the name

df.loc[0, 'Salary']

100000

In [ ]:
df2=df
df2=df2.set_index("Name")
df2.head()

ID       Department  Salary
Name                             
Rose   1  Architect Group  100000
John   2   Software Group   80000
Jane   3      Design Team   50000
Mary   4   Infrastructure   60000

In [ ]:
df2.loc['Jane', 'Salary']

50000

In [ ]:
df2.loc['Jane', 'Department']

'Design Team'

In [ ]:
df2.iloc[3,2]

60000

In [ ]:
# let us do the slicing using old dataframe df

df.iloc[0:2, 0:3]

Name  ID       Department
0  Rose   1  Architect Group
1  John   2   Software Group

In [ ]:
#let us do the slicing using loc() function on old dataframe df where index column is having labels as 0,1,2
df.loc[0:2,'ID':'Department']

ID       Department
0   1  Architect Group
1   2   Software Group
2   3      Design Team

In [ ]:
#let us do the slicing using loc() function on new dataframe df1 where index column is Name having labels: Rose, John and Jane
df2.loc['Rose':'Jane', 'ID':'Department']

ID       Department
Name                     
Rose   1  Architect Group
John   2   Software Group
Jane   3      Design Team

In [ ]:
df.loc[2:3,'Name':'Department']

Name  ID      Department
2  Jane   3     Design Team
3  Mary   4  Infrastructure

In [ ]:
import pandas as pd

In [10]:
import numpy as np
a=[1,2,3,4,5]
type(a)


numpy.dtype

In [15]:
np.shape(a)

(5,)

In [17]:
np.dtype


numpy.dtype

In [18]:
np.mean(a)

3.0

In [19]:
# Create a python list

a = ["0", 1, "two", "3", 4]

In [20]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


In [21]:
# import numpy library

import numpy as np 

In [22]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [23]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [24]:
print(np.__version__)

1.21.6


In [25]:
# Check the type of the array

type(a)

numpy.ndarray

In [26]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int64')

In [27]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])


# type(b)
b.dtype

dtype('float64')

In [31]:
type(b)
    
b.dtype

dtype('float64')

In [32]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [33]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [34]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

In [35]:
a = np.array([10, 2, 30, 40,50])


a[1]=50
a

array([10, 50, 30, 40, 50])

In [36]:
d = c[1:4]
d

array([1, 2, 3])

In [37]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [39]:
print(arr[:4])

[1 2 3 4]


In [40]:
print(arr[4:])

[5 6 7]


In [41]:
print(arr[1:5:])

[2 3 4 5]


In [43]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])


print(arr[1:8:2])

[2 4 6 8]


In [44]:
# Create the index list

select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

In [45]:
d = c[select]
d

array([100,   2, 300, 400])

In [46]:
# Assign the specified elements to new value

c[select] = 100000
c

array([100000,      1, 100000, 100000, 100000])

In [47]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [48]:
a.size

5

In [49]:
a.shape

(5,)

In [50]:
b = np.array([10, 20, 30, 40, 50, 60, 70])


print(b.size)
print(b.ndim)
print(b.shape)


7
1
(7,)


In [51]:
# Create a numpy array

a = np.array([1, -1, 1, -1])

In [52]:
# Get the mean of numpy array

mean = a.mean()
mean

0.0

In [53]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

1.0

In [54]:
# Create a numpy array

b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [55]:
# Get the biggest value in the numpy array

max_b = b.max()
max_b

5

In [56]:
# Get the smallest value in the numpy array

min_b = b.min()
min_b

-1

In [57]:
c = np.array([-10, 201, 43, 94, 502])


max_c = c.max()
print(max_c)
    
min_c = c.min()
print(min_c)
    
    
Sum = (max_c +min_c)
print(Sum)

502
-10
492


In [59]:
# Write your code below and press Shift+Enter to execute

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
A.size

12

In [61]:
A[0][0:2]

array([1, 2])

In [62]:
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
X = np.dot(A,B)
X

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])

In [64]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [65]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [70]:
a=np.array([1,1,1,1,1])

a+10


array([11, 11, 11, 11, 11])